### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by sunbeibei-hub** [reazon-research/ReazonSpeech#30]
my code is :
```
from reazonspeech.nemo.asr import load_model, transcribe, audio_from_path

# 実行時にHugging Faceからモデルを取得します (2.3GB)
model = load_model(device='cuda')

# ローカルの音声ファイルを読み込む
audio = audio_from_path('speech-001.wav')

# 音声認識を適用する
ret = transcribe(model, audio)

print(ret.text)
~             


this is error:
```
Traceback (most recent call last):
  File "/data/bei/bei_test.py", line 4, in <module>
    model = load_model(device='cuda')
  File "/root/miniconda/envs/bei_ReazonSpeech/lib/python3.9/site-packages/reazonspeech/nemo/asr/transcribe.py", line 26, in load_model
    from nemo.collections.asr.models import EncDecRNNTBPEModel
  File "/root/miniconda/envs/bei_ReazonSpeech/lib/python3.9/site-packages/nemo/collections/asr/__init__.py", line 15, in <module>
    from nemo.collections.asr import data, losses, models, modules
  File "/root/miniconda/envs/bei_ReazonSpeech/lib/python3.9/site-packages/nemo/collections/asr/losses/__init__.py", line 16, in <module>
    from nemo.collections.asr.losses.audio_losses import SDRLoss
  File "/root/miniconda/envs/bei_ReazonSpeech/lib/python3.9/site-packages/nemo/collections/asr/losses/audio_losses.py", line 21, in <module>
    from nemo.collections.asr.parts.preprocessing.features import make_seq_mask_like
  File "/root/miniconda/envs/bei_ReazonSpeech/lib/python3.9/site-packages/nemo/collections/asr/parts/preprocessing/__init__.py", line 16, in <module>
    from nemo.collections.asr.parts.preprocessing.features import FeaturizerFactory, FilterbankFeatures, WaveformFeaturizer
  File "/root/miniconda/envs/bei_ReazonSpeech/lib/python3.9/site-packages/nemo/collections/asr/parts/preprocessing/features.py", line 44, in <module>
    from nemo.collections.asr.parts.preprocessing.perturb import AudioAugmentor
  File "/root/miniconda/envs/bei_ReazonSpeech/lib/python3.9/site-packages/nemo/collections/asr/parts/preprocessing/perturb.py", line 50, in <module>
    from nemo.collections.common.parts.preprocessing import collections, parsers
  File "/root/miniconda/envs/bei_ReazonSpeech/lib/python3.9/site-packages/nemo/collections/common/__init__.py", line 16, in <module>
    from nemo.collections.common import data, losses, parts, tokenizers
  File "/root/miniconda/envs/bei_ReazonSpeech/lib/python3.9/site-packages/nemo/collections/common/tokenizers/__init__.py", line 17, in <module>
    from nemo.collections.common.tokenizers.canary_tokenizer import CanaryTokenizer
  File "/root/miniconda/envs/bei_ReazonSpeech/lib/python3.9/site-packages/nemo/collections/common/tokenizers/canary_tokenizer.py", line 51, in <module>
    class CanaryTokenizer(AggregateTokenizer):
  File "/root/miniconda/envs/bei_ReazonSpeech/lib/python3.9/site-packages/nemo/collections/common/tokenizers/canary_tokenizer.py", line 105, in CanaryTokenizer
    def build_special_tokenizer(output_dir: str | Path) -> SentencePieceTokenizer:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

my env:
❯ pip list
Package                  Version
------------------------ ------------
absl-py                  2.1.0
aiohttp                  3.9.5
aiosignal                1.3.1
antlr4-python3-runtime   4.9.3
asttokens                2.4.1
async-timeout            4.0.3
attrs                    23.2.0
audioread                3.0.1
braceexpand              0.1.7
certifi                  2024.7.4
cffi                     1.16.0
charset-normalizer       3.3.2
click                    8.1.7
comm                     0.2.2
contourpy                1.2.1
cycler                   0.12.1
Cython                   3.0.10
cytoolz                  0.12.3
datasets                 2.20.0
decorator                5.1.1
dill                     0.3.8
Distance                 0.1.3
docker-pycreds           0.4.0
docopt                   0.6.2
editdistance             0.8.1
exceptiongroup           1.2.1
executing                2.0.1
filelock                 3.15.4
fonttools                4.53.1
frozenlist               1.4.1
fsspec                   2024.5.0
future                   1.0.0
g2p-en                   2.1.0
gitdb                    4.0.11
GitPython                3.1.43
grpcio                   1.64.1
huggingface-hub          0.23.4
hydra-core               1.3.2
idna                     3.7
importlib_metadata       8.0.0
importlib_resources      6.4.0
inflect                  7.3.1
intervaltree             3.1.0
ipython                  8.18.1
ipywidgets               8.1.3
jedi                     0.19.1
Jinja2                   3.1.4
jiwer                    3.0.4
joblib                   1.4.2
jupyterlab_widgets       3.0.11
kaldi-python-io          1.2.2
kaldiio                  2.18.0
kiwisolver               1.4.5
lazy_loader              0.4
Levenshtein              0.25.1
lhotse                   1.24.2
librosa                  0.10.2.post1
lightning-utilities      0.11.3.post0
lilcom                   1.8.0
llvmlite                 0.43.0
loguru                   0.7.2
Markdown                 3.6
markdown-it-py           3.0.0
MarkupSafe               2.1.5
marshmallow              3.21.3
matplotlib               3.9.1
matplotlib-inline        0.1.7
mdurl                    0.1.2
more-itertools           10.3.0
mpmath                   1.3.0
msgpack                  1.0.8
multidict                6.0.5
multiprocess             0.70.16
nemo_toolkit             1.23.0
networkx                 3.2.1
nltk                     3.8.1
numba                    0.60.0
numpy                    1.26.4
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.20.5
nvidia-nvjitlink-cu12    12.5.82
nvidia-nvtx-cu12         12.1.105
omegaconf                2.3.0
onnx                     1.16.1
packaging                24.1
pandas                   2.2.2
parso                    0.8.4
pexpect                  4.9.0
pillow                   10.4.0
pip                      24.0
plac                     1.4.3
platformdirs             4.2.2
pooch                    1.8.2
prompt_toolkit           3.0.47
protobuf                 4.25.3
psutil                   6.0.0
ptyprocess               0.7.0
pure-eval                0.2.2
pyannote.core            5.0.0
pyannote.database        5.1.0
pyannote.metrics         3.2.1
pyarrow                  16.1.0
pyarrow-hotfix           0.6
pybind11                 2.13.1
pycparser                2.22
pydub                    0.25.1
Pygments                 2.18.0
pyloudnorm               0.1.1
pyparsing                3.1.2
python-dateutil          2.9.0.post0
pytorch-lightning        2.0.7
pytz                     2024.1
PyYAML                   6.0.1
rapidfuzz                3.9.4
reazonspeech-nemo-asr    2.0.1
regex                    2024.5.15
requests                 2.32.3
resampy                  0.4.3
rich                     13.7.1
ruamel.yaml              0.18.6
ruamel.yaml.clib         0.2.8
sacremoses               0.1.1
safetensors              0.4.3
scikit-learn             1.5.1
scipy                    1.13.1
sentencepiece            0.2.0
sentry-sdk               2.7.1
setproctitle             1.3.3
setuptools               69.5.1
shellingham              1.5.4
six                      1.16.0
smmap                    5.0.1
sortedcontainers         2.4.0
soundfile                0.12.1
sox                      1.5.0
soxr                     0.3.7
stack-data               0.6.3
sympy                    1.12.1
tabulate                 0.9.0
tensorboard              2.17.0
tensorboard-data-server  0.7.2
termcolor                2.4.0
text-unidecode           1.3
texterrors               0.5.1
threadpoolctl            3.5.0
tokenizers               0.19.1
toolz                    0.12.1
torch                    2.3.1
torchmetrics             1.4.0.post0
tqdm                     4.66.4
traitlets                5.14.3
transformers             4.42.3
triton                   2.3.1
typeguard                4.3.0
typer                    0.12.3
typing_extensions        4.12.2
tzdata                   2024.1
urllib3                  2.2.2
wandb                    0.17.4
wcwidth                  0.2.13
webdataset               0.1.62
Werkzeug                 3.0.3
wget                     3.2
wheel                    0.43.0
widgetsnbextension       4.0.11
wrapt                    1.16.0
xxhash                   3.4.1
yarl                     1.9.4
youtokentome             1.0.6
zipp                     3.19.2

my python version is : 
python==3.9.19

please me. thank you!

**Comment by fujimotos** [comment]
> my python version is :
> python==3.9.19

Nvidia NeMo support Python 3.10 or later. Py3.9 support was dropped
a while ago. Quoting from https://github.com/NVIDIA/NeMo:

> ### Requirements
> - Python 3.10 or above
> - Pytorch 1.13.1 or above
> - NVIDIA GPU (if you intend to do model training)

You'll need to upgrade your python version.

**Comment by sunbeibei-hub** [comment]
thank you， i will try it.
