### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by root20** [reazon-research/ReazonSpeech#40]
Hello, I'm trying to download the dataset using lhotse, and I got this error. How do I fix it?

```
2024-11-13 01:29:27,450 INFO [reazonspeech.py:98] Downloading ReazonSpeech part: small
Traceback (most recent call last):
  File "/opt/conda/bin/lhotse", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/lhotse/bin/modes/recipes/reazonspeech.py", line 52, in reazonspeech
    download_reazonspeech(target_dir, dataset_parts=subset)
  File "/opt/conda/lib/python3.10/site-packages/lhotse/recipes/reazonspeech.py", line 99, in download_reazonspeech
    ds = load_dataset(
  File "/opt/conda/lib/python3.10/site-packages/datasets/load.py", line 2128, in load_dataset
    builder_instance = load_dataset_builder(
  File "/opt/conda/lib/python3.10/site-packages/datasets/load.py", line 1851, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/opt/conda/lib/python3.10/site-packages/datasets/builder.py", line 373, in __init__
    self.config, self.config_id = self._create_builder_config(
  File "/opt/conda/lib/python3.10/site-packages/datasets/builder.py", line 561, in _create_builder_config
    raise ValueError(f"BuilderConfig {builder_config} doesn't have a '{key}' key.")
ValueError: BuilderConfig ReazonSpeechConfig(name='small', version=0.0.0, data_dir=None, data_files=None, description=None) doesn't have a 'trust_remote_code' key.
```

**Comment by fujimotos** [comment]
> ValueError: BuilderConfig ReazonSpeechConfig(name='small', version=0.0.0, data_dir=None, data_files=None, description=None) doesn't have a 'trust_remote_code' key.

Probably you are using an ancient version of `datasets` package.
Try upgrading the package to the latest version.

**Comment by root20** [comment]
It works thank you for the quick response!!
